version: '3.8'

services:
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80" # 호스트의 3000번 포트를 컨테이너의 80번 포트(Nginx)와 연결
    depends_on:
      - backend-service
